### ISSUE TITLE
Error reading Gender

### ISSUE THREAD

**Issue by pwhe23** [penguinboy/Eventbrite.NET#1]
I am really glad I found this project, saved me some work. I did have one issue though. This code was failing for me:

```
var gender = TryGetElementNullableIntValue("gender", doc);
if (gender != null)
{
    toReturn.Gender = (AttendeeGender)gender;
}
```

I fixed it by using this code:

```
toReturn.Gender = (AttendeeGender)Enum.Parse(typeof (AttendeeGender), TryGetElementValue("gender", doc));
```

Feel free to use it if that helps.

**Comment by penguinboy** [comment]
Thanks for that. I'll get to verifying and fixing this ASAP.

**Comment by penguinboy** [comment]
I just had a look at implementing your fix, but it doesn't seem to take null values into account. The Eventbrite API will only return gender values if the attendee has entered them into the system. In all of the attendees I have access to, none of them have a set gender, hence why I haven't spotted this before.

According to the [API documentation](http://developer.eventbrite.com/doc/events/event_list_attendees/), genders should be passed back as "M" or "F". However, the documentation is notoriously flaky. Can you confirm that the code below works with your attendees that have gender information?

It's not as nice as a one-liner, but at least it's readable.
    var gender = TryGetElementValue("gender", doc);
    if (gender == "M")
    {
        toReturn.Gender = AttendeeGender.Male;
    }
    else if (gender == "F")
    {
        toReturn.Gender = AttendeeGender.Female;
    }

**Comment by pwhe23** [comment]
When I tested it I was getting the full gender string back, "Female" and "Male". I didn't test with nulls, but I think the code below would handle that.

```
string gender = TryGetElementValue("gender", doc);
if (!String.IsNullOrEmpty(gender)) {
    toReturn.Gender = (AttendeeGender) Enum.Parse(typeof (AttendeeGender), gender);
}
```

**Comment by pwhe23** [comment]
Whoops, didn't mean to close it

**Comment by penguinboy** [comment]
I've just pushed the fix you provided. Thanks a lot!
