### ISSUE TITLE
Where do I get the Organizer Id in EventBrite?

### ISSUE THREAD

**Issue by balmeter** [penguinboy/Eventbrite.NET#2]
I cannot find the organizer id in my Eventbrite account?

Sorry for the ignorance, Thanks in advance.

Brian

**Comment by penguinboy** [comment]
When you're logged in the admin side of things you should see a link to "My Events". The number in the URL is your id.

http://help.wisestamp.com/email-apps/username/eventbrite-how-do-i-find-my-organizer-id

**Comment by balmeter** [comment]
Thanks for responding, I figured it out.

I had another issue though. I found that my organizer Id was not a valid Int32, so I was getting an error. My organizer Id was larger than an Int32. I downloaded the project and modified the code to make it a Int64 and it works.

Now, do you want to upgrade it? Should I put in a bug report? Iall for opensource, but I prefer modificationof the source be done by theowner.Below is the code in Organizer.cs, then affects other classes.

Let me know if you update it. I can compile a DLL for my site, but I would rather utilize your version.

Brian
private
Dictionary<Int64, Event> events;
publicDictionary<Int64, Event> Events{
get{
if(events == null){
events = 
newDictionary<Int64, Event>();
vareventArray = newOrganizerEventsRequest(this.Id, Context).GetResponse();
foreach(vareventEntity ineventArray){
events.Add(eventEntity.Id, eventEntity);
}
}
returnevents;}
}

**Comment by penguinboy** [comment]
From looking at http://developer.eventbrite.com/doc/organizers/organizer_list_events/ I can see that organiser id's are actually supposed to be strings.... hmmm...

The code you sent seems to infer that _event_ ids are 64 bit. I'm investigating the issue, I'll get back to you when I've made a commit.

Thanks for your help!

**Comment by penguinboy** [comment]
Fixes have finally been merged into the main repo.
