### ISSUE TITLE
APIRequest > GetRequest() Bug!

### ISSUE THREAD

**Issue by MeniroDev** [penguinboy/Eventbrite.NET#3]
Currently your GetRequest code contains:
           var client = new WebClient();
           return client.DownloadString(this.Url);

For some reason, if you retrieve a specific Event (by ID) and the events description contains:
left quote  (’)
right quote (‘)
or a dash  (-)
and other non AlphaNumerics (only some though) they get interpreted by the WebClient as random characters.

For example:
"he said ’no place like home‘ very loudly"
in the event description, will come back from the WebClient request as:
"he said Ä€™no place like homeÄ€™ very loudly"

Simply swap out:
           var client = new WebClient();
           return client.DownloadString(this.Url);

for:
            HttpWebRequest request = (HttpWebRequest)
            WebRequest.Create(this.Url);
            HttpWebResponse response = (HttpWebResponse)
            request.GetResponse();
            Stream stream = response.GetResponseStream();
            StreamReader sr = new StreamReader(stream);
            return sr.ReadToEnd();

Cheers :)

**Comment by penguinboy** [comment]
I've merged this change into the main repo. Let me know if you have any issues.
