### ISSUE TITLE
Organizer ID Is now Higher than Int, it requires to be updated to Int64

### ISSUE THREAD

**Issue by luismgonzalezb** [penguinboy/Eventbrite.NET#6]
I have a Organizer Id that is higher than Int, I can't move on because of this. Update to Int64 is required

**Comment by dampee** [comment]
Send a pull request for this: https://github.com/penguinboy/Eventbrite.NET/pull/7
if you want to change it on your local machine: the only file to change is the EventbriteContext (change int to long).

**Comment by penguinboy** [comment]
#7 has been merged. This shouldn't be an issue any more.
